// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gblkznstpusuusefovvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdibGt6bnN0cHVzdXVzZWZvdnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzA1MDcsImV4cCI6MjA3NDU0NjUwN30.Nx7Wi1ftyoZxdZPyNMerKZBpJb1N61Axk0uGZ1flBzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});